hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "fa34a3117af7f8ed553ec563a7c90c1d6462184c7df5b837c831cb482c6ae582"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "5ac32407263c973bebc5aee61fe000d29d9879020fafb6631581396b64e55dfe"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "c1fb4b35943ed603eaaa2999ec0faa3d22a5ea2a95f7ef1b0cd0eae83c945bae"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "39f4971b06139614f03993ffc73e3a1d39e061813690eb1edffe2215c148ffa7"
metafile = true
