hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "0a1d5aeaae3975eaa4bb3a98e91852f797a5095794af70df41d50841c57ca347"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "fa34a3117af7f8ed553ec563a7c90c1d6462184c7df5b837c831cb482c6ae582"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "45bfe44cb3208de7ce385b6a3e98251e7423c5aac8ebec9c13c752b75661d793"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "5ac32407263c973bebc5aee61fe000d29d9879020fafb6631581396b64e55dfe"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fb8e035187556a9406507176782dd251769d8cdf14e9712b508bcc47ff6904d9"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "2a50d21837bba88e3c9490c6bb8e0a9b44b052645d5c1481b48a060439c20a3c"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "c1fb4b35943ed603eaaa2999ec0faa3d22a5ea2a95f7ef1b0cd0eae83c945bae"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "1ff2d8ad68c4c66a92454a917ab0e383ac67872e56832bf80559a724c8845041"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "ea7f91e66e1e475cd5fa10f56caa46a6a53754da99ed3252e6a6f68b731699b1"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "39f4971b06139614f03993ffc73e3a1d39e061813690eb1edffe2215c148ffa7"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "35905f57cdb21a2aaa26345f2fabe3137ee2db6ee3bb2149cea206611b11ef69"
metafile = true

[[files]]
file = "mods/the-one-probe.pw.toml"
hash = "efa0c67ad2b85494d075f5028ac3b95e621b65861355f41c039bf9830e4192ed"
metafile = true
