name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "befae75dd99d0cc099c81ce4acd17bf90c5c5a5bf24233ff6fa2b64b897a59fe"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
