name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60310cdf260968a2244f6dae21387512a56c09cd778640b32695d66d1aebab50"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
