name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.16.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ac1d3be22ad7455682afdd6ee001677dddb46926eb147cbf73bf8fef9ad615d"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
