name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f346561703bc0dcd5021274601ecc744952d46b197314b1ca3993b12b298781a"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
