name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fe3b0dcb8efdf6d86098f809c6d71db74547c7e70f2a7f01cd98b12b91f0744"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
