name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.15.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c53e26e0d8f10130cd6b786bded13720fbe0d052b96b7065e633264af10c047"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
