name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddb52d6a1afbaa798596e946fa8b20a9d7a8ea1436c72ddebcdf82349acc6aab"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
