name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8446d9d631ba401c0aa98786f3aae85c86e00d09c3750d22b4379673bd43ace"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
