name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48ca273e5fcb73cd8ed28dc6a49cbf7b8b4d001a4b610ed7776d12527f5a8221"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
