name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "0.18.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bed4b982c1c25d1a0a9729e4abe56cf791be9b20c439a8bdf830e564b2e862d2"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
